blank_issues_enabled: false
contact_links:
  - name: 💬 Discord Community
    url: https://discord.gg/emoji-hunt
    about: Join our Discord for questions and discussions
  - name: 📚 Documentation
    url: https://github.com/djs5008/emoji-hunt/wiki
    about: Check our wiki for guides and FAQs